#!/usr/bin/env node
const prog = require('caporal');
const chalk = require('chalk');

prog
  .version('1.0.0')
  .command('events')
  .option('--city <kind>', 'Kind of pizza', ['paris', 'lyon'], 'paris')
  .option('--exclude <excludeL>', prog.LIST)
  .option('--days <daysL>', prog.LIST)
  .option('--summary <sum>', prog.BOOL)
  .action(function(args, options) {
    console.log(chalk.magenta('Make HTTP request here with this body:'));
    console.log(options);
  });

prog.parse(process.argv);
